version: '3'

set: [errexit, nounset, pipefail]

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list
    silent: true

  install:
    desc: Install dependencies
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/**

  dev:
    desc: Start Vite dev server (:5173)
    cmds:
      - npm run dev

  build:
    desc: Build for production
    cmds:
      - npm run build

  test:
    desc: Run tests
    cmds:
      - npm run test

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - npm run test:watch

  test:coverage:
    desc: Run tests with coverage (≥85% enforced)
    cmds:
      - npm run test:coverage

  lint:
    desc: Lint TypeScript code
    cmds:
      - npx eslint src

  fmt:
    desc: Format code with Prettier
    cmds:
      - npm run fmt

  fmt:check:
    desc: Check formatting without writing
    cmds:
      - npm run fmt:check

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - npm run typecheck

  check:
    desc: Pre-commit checks (fmt, lint, typecheck, test:coverage)
    cmds:
      - task: fmt
      - task: lint
      - task: typecheck
      - task: test:coverage
      - echo "✓ All checks passed"
